pub mod agent_handling;
pub mod app;
pub mod components;
pub mod event_handler;
pub mod fuzzy_finder;
pub mod layout;
pub mod slash;
pub mod snapshot_capture;
pub mod state;
pub mod syntax;
pub mod theme;
pub mod transcript;
pub mod tui_approval;

pub use app::App;
pub use event_handler::{EventHandler, KeyAction};
pub use fuzzy_finder::{FileEntry, FuzzyFinder, SortMode};
pub use snapshot_capture::{SnapshotCapture, SnapshotMode};
pub use state::{AppState, ComposerMode, InputState};
pub use syntax::SyntaxHighlighter;
pub use theme::{Theme, ThemeVariant};
pub use transcript::{ApprovalDecision, Transcript, TranscriptEntry, TranscriptRenderer};
pub use tui_approval::TuiApprovalHandle;
