[package]
name = "thndrs-ui"
version = "0.1.0"
edition = "2024"

[dependencies]
thndrs-core = { path = "../core" }
thndrs-mem = { path = "../memory" }

crossterm = { version = "0.28", features = ["event-stream"] }
thiserror = "2.0"
tracing = "0.1"
tokio = { version = "1", features = ["rt-multi-thread"] }
ignore = "0.4"
syntect = { version = "5", default-features = true }
nucleo-matcher = "0.3"
dirs = "6.0"
chrono = "0.4"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
toml = "0.8"
iocraft = "0.7.18"
smol = "2.0.2"

[dev-dependencies]
futures = "0.3"

[lints]
workspace = true
